
<!-- saved from url=(0041)http://math.hws.edu/javanotes8/c3/s7.html -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>Javanotes 8.0, Section 3.7 -- Introduction to Exceptions and try..catch</title>
<link type="text/css" rel="stylesheet" href="javanotes.css">
</head>
<body>
<div class="page">
<div class="content">
<h3 class="section_title">Section 3.7</h3>
<h2 class="section_title">Introduction to Exceptions and try..catch</h2>
<hr class="break">


<h3 class="subsection_title">
<a name="control.7.2">3.7.2&nbsp;&nbsp;try..catch</a>
</h3>
   

<p>When an exception occurs, we say that the exception is "thrown."
For example, we say that <span class="code">Integer.parseInt(str)</span> <span class="newword">throws</span>
an exception of type <span class="classname">NumberFormatException</span> when the value of 
<span class="code">str</span> is illegal.  When an exception is thrown, it is possible
to "catch" the exception and prevent it from crashing the program.  This is
done with a <span class="newword">try..catch</span> statement.  In simplified
form, the syntax for a <span class="code">try..catch</span> statement can be:</p>


<pre>try {
   <span class="bnf">statements-1</span>
}
catch ( <span class="bnf">exception-class-name</span>  <span class="bnf">variable-name</span> ) {
   <span class="bnf">statements-2</span>
}</pre>
   

<p>The <span class="bnf">exception-class-name</span> could be <span class="classname">NumberFormatException</span>,
<span class="classname">IllegalArgumentException</span>, or some other exception class.
When the computer executes this <span class="code">try..catch</span> statement, 
it executes <span class="bnf">statements-1</span>, the statements inside the <span class="code">try</span>
part.  If no exception occurs during the execution of <span class="bnf">statements-1</span>, then the computer
just skips over the <span class="code">catch</span> part and proceeds with the rest of the program.
However, if an exception of type <span class="bnf">exception-class-name</span> occurs during the
execution of <span class="bnf">statements-1</span>, the computer immediately jumps from the point where the
exception occurs to the
<span class="code">catch</span> part and executes <span class="bnf">statements-2</span>, skipping any remaining statements in
<span class="bnf">statements-1</span>.  
Note that only one type of exception is caught; if some other type of exception occurs
during the execution of <span class="bnf">statements-1</span>, it will crash the program as usual.
</p>

<p>During the execution of <span class="bnf">statements-2</span>, the
<span class="bnf">variable-name</span> represents the exception object, so that you can, for example,
print it out.  The exception object contains information about the cause of the exception.
This includes an error message, which will be displayed if you print out the exception object.</p>


<p>After the end of the
<span class="code">catch</span> part, the computer proceeds with the rest of the program;
the exception has been caught and handled and does not crash the program.
</p>
   

<p>By the way, note that the braces, { and }, are part of the syntax of the
<span class="code">try..catch</span> statement.  They are required even if there is only one
statement between the braces.  This is different from the other statements we
have seen, where the braces around a single statement are optional.</p>
   

<p>As an example, suppose that <span class="code">str</span> is a variable of type <span class="classname">String</span>
whose value might or might not represent a legal real number.  Then we could say:</p>
   

<pre>double x;
try {
   x = Double.parseDouble(str);
   System.out.println( "The number is " + x );
}
catch ( NumberFormatException e ) {
   System.out.println( "Not a legal number." );
   x = Double.NaN;
}</pre>
   

<p>If an error is thrown by the call to <span class="code">Double.parseDouble(str)</span>, then the
output statement in the <span class="code">try</span> part is skipped, and the statement in the
<span class="code">catch</span> part is executed.  (In this example, I set <span class="code">x</span> to be
the value <span class="code">Double.NaN</span> when an exception occurs.  <span class="code">Double.NaN</span>
is the special "not-a-number" value for type <span class="ptype">double</span>.)
</p>
   

<p>It's <b>not</b> always a good idea to catch exceptions and continue with the program.  Often
that can just lead to an even bigger mess later on, and it might be better just to let
the exception crash the program at the point where it occurs.  However, sometimes it's
possible to recover from an error.</p>


<p>Suppose, for example, we want a program that will
find the average of a sequence of real numbers entered by the user, and we want the user
to signal the end of the sequence by entering a blank line.  (This is similar
to the sample program <span class="sourceref"><a href="http://math.hws.edu/javanotes8/source/chapter3/ComputeAverage.java">ComputeAverage.java</a></span> from <a href="http://math.hws.edu/javanotes8/c3/s3.html">Section&nbsp;3.3</a>,
but in that program the user entered a zero to signal end-of-input.)
If we use <span class="code">TextIO.getlnInt()</span>
to read the user's input, we will have no way of detecting the blank line, since that
function simply skips over blank lines.  A solution is to use <span class="code">TextIO.getln()</span>
to read the user's input.  This allows us to detect a blank input line, and we can
convert non-blank inputs to numbers using <span class="code">Double.parseDouble</span>.  And we
can use <span class="code">try..catch</span> to avoid crashing the program when the user's input
is not a legal number.  Here's the program:</p>


<pre>import textio.TextIO;

public class ComputeAverage2 {

   public static void main(String[] args) {
       String str;     // The user's input.
       double number;  // The input converted into a number.
       double total;   // The total of all numbers entered.
       double avg;     // The average of the numbers.
       int count;      // The number of numbers entered.
       total = 0;
       count = 0;
       System.out.println("Enter your numbers, press return to end.");
       while (true) {
          System.out.print("? ");
          str = TextIO.getln();
          if (str.equals("")) {
             break; // Exit the loop, since the input line was blank.
          }
          try {
              number = Double.parseDouble(str);
              // If an error occurs, the next 2 lines are skipped!
              total = total + number;
              count = count + 1;
          }
          catch (NumberFormatException e) {
              System.out.println("Not a legal number!  Try again.");
          }
       }
       avg = total/count;
       System.out.printf("The average of %d numbers is %1.6g%n", count, avg);
   }

}</pre>

</div>
<hr>
</div>


<div id="UMS_TOOLTIP" style="position: absolute; cursor: pointer; z-index: 2147483647; background: transparent; top: -100000px; left: -100000px;"></div></body><umsdataelement id="UMSSendDataEventElement"></umsdataelement><div id="TAG_ID4TOOLBAR_UMS_GUID" style="display: none;">06A13793-E62C-5E65-1D8D-62085C592BB8</div><div id="tmtoolbar_ums_injected" style="display: none;">init_ums</div></html>